### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by wendtke** [SmogDr/edar_coursebook#11]
This issue can track running questions about style preferences and consistency throughout the book. 

@SmogDr 

- Would you like all of the quotes to be in blue font? I noticed they are gray in early chapters and blue starting in Chapter 4.

**Comment by SmogDr** [comment]
Yes! I like the distinction.

jv

--
John Volckens
Professor, Mechanical Engineering
Colorado State University
he, him, his
jv.colostate.edu<http://jv.colostate.edu/> / @Smogdr

On Jul 20, 2020, at 9:37 PM, Kathleen Wendt <notifications@github.com> wrote:

﻿

This issue can track running questions about style preferences and consistency throughout the book.

@SmogDr<https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSmogDr&data=02%7C01%7Cjohn.volckens%40colostate.edu%7Cc98c88dbd1284e6cc89708d82d277472%7Cafb58802ff7a4bb1ab21367ff2ecfc8b%7C0%7C0%7C637308994768458123&sdata=gkZqKKNtWrRLFhNnCp20dULhYihleab%2Bdk5RqMMsdRw%3D&reserved=0>

  *   Would you like all of the quotes to be in blue font? I noticed they are gray in early chapters and blue starting in Chapter 4.

**Comment by wendtke** [comment]
- No spaces or underscores (use dashes) in chunk options

**Comment by wendtke** [comment]
I have made these updates for Chapters 1-4. Chapter 5 onward, all quotes will be blue, and chunk options will follow Yihui's guidance.
