### ISSUE TITLE
Cloud for binary files

### ISSUE THREAD

**Issue by wendtke** [SmogDr/edar_coursebook#12]
@SmogDr, we briefly discussed creating a shared Google Drive or at least a folder for this course. I think it would helpful to have binary files like the annotations.pptx in Google Drive. Git hates binary files and is confused by iCloud update attempts. Plus, the file is bigger than GitHub's recommendation for commits. 

What do you think?

**Comment by SmogDr** [comment]
@wendtke Would Dropbox be OK?  Google Drive is clumsy with MS Office products like Word and Powerpoint...always trying to convert them...

**Comment by wendtke** [comment]
Good point. CSU OneDrive or general Dropbox is fine with me.

**Comment by SmogDr** [comment]
@wendtke I sent a Dropbox sharing link via email (couldn't figure out an html link that gave edit access).
