### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by wendtke** [SmogDr/edar_coursebook#15]
It looks like Brooke's train pictures from Chapter 2 are missing. Did you remove them from /figures, @SmogDr ?

**Comment by SmogDr** [comment]
Strange.  I noticed the same error this weekend but I thought I had corrected that by pushing them back up!

--
John Volckens
Professor, Mechanical Engineering
Colorado State University
he, him, his
jv.colostate.edu / @Smogdr

**Comment by wendtke** [comment]
I might have figured out why this was happening. My iCloud Drive was holding the images but not allowing them to download locally, so every time I pulled your work down, it got confused. I think I solved it, so I'll close this. I'll keep an eye on this and reopen the issue if it happens again.
