### ISSUE TITLE
Creating R project

### ISSUE THREAD

**Issue by wendtke** [SmogDr/edar_coursebook#16]
Guidance on creating and structuring a class R project in the course set-up section of Chapter 1. 

MECH481A6.Rproj
- /data-raw
- /data-clean
- /code
- /figs
- /homework
etc.

**Comment by wendtke** [comment]
@SmogDr do you want each student to have a ***private*** GitHub repository for the classwork with us as collaborators? That way, independent learning may be more likely, but they can also communicate with us directly for feedback.

**Comment by SmogDr** [comment]
Yes, I think they should be private.

--
John Volckens
Professor, Mechanical Engineering
Colorado State University
he, him, his
jv.colostate.edu / @Smogdr

**Comment by wendtke** [comment]
See #17
