### ISSUE TITLE
R project & GitHub set-up / best practices

### ISSUE THREAD

**Issue by wendtke** [SmogDr/edar_coursebook#17]
@SmogDr, would you like students to submit homework via Canvas or GitHub? Brooke had us email her links to the GitHub files. Early in the semester, we emailed her Word documents (`swirl` [instructions](https://geanders.github.io/RProgrammingForResearch/appendix-b-homework.html)) or R Markdown files knitted to PDF. 

Do you think the students will be set up in and using GitHub in time for the first homework submission?

**Comment by wendtke** [comment]
Add GitHub information in Chapter 1 

[Day Zero](https://github.com/uncoast-unconf/uu-2019-day-zero)
[Happy Git](https://happygitwithr.com/)

**Comment by wendtke** [comment]
Weeks 1-2
1. Install R/RStudio; OS-specific [installations](https://rstats.wtf/set-up-an-r-dev-environment.html) like Xcode on Mac
2. Create GitHub repo (private; add @SmogDr and @wendtke as collaborators) with these [instructions](https://happygitwithr.com/new-github-first.html). Optional lecture on git/GitHub [background](https://uncoast-unconf.github.io/uu-2019-day-zero/01-git-github-cornucopia/git-github-cornucopia.html#).
3. Create MECH481A6.Rproj with [this](https://uncoast-unconf.github.io/uu-2019-day-zero/02-project-workflows/workflow.html#13) directory structure.
4. Confirm git/GitHub connection to/from R project.

**a [comprehensive](https://github.com/uncoast-unconf/uu-2019-day-zero/blob/master/00-preparation/README.md) R developer set-up, if students are interested in developing and sharing R packages eventually

**Comment by wendtke** [comment]
> @SmogDr, would you like students to submit homework via Canvas or GitHub? Brooke had us email her links to the GitHub files. Early in the semester, we emailed her Word documents (`swirl` [instructions](https://geanders.github.io/RProgrammingForResearch/appendix-b-homework.html)) or R Markdown files knitted to PDF.
> 
> Do you think the students will be set up in and using GitHub in time for the first homework submission?

We want GitHub submissions but do all students have their own computers? @SmogDr to inquire

**Comment by wendtke** [comment]
The PR related to this issue will also address #14 (best practices for R project and git/GitHub) and #16 (private GitHub repository for each student).

**Comment by wendtke** [comment]
@SmogDr - do you want to create a GitHub [organization](https://happygitwithr.com/classroom-overview.html) with the students' private repos, or just have students host their own on their individual profiles? See [here](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/collaborating-with-groups-in-organizations) for more info.

**Comment by wendtke** [comment]
@SmogDr - see https://twitter.com/tiana_athriel/status/1292962508173533184?s=21

Do you envision going through installation together in class, or should I include screenshots in this PR?

**Comment by SmogDr** [comment]
I think we will do it in class but I would include the screenshots, too.

--
John Volckens
Professor, Mechanical Engineering
Colorado State University
he, him, his
jv.colostate.edu / @Smogdr

**Comment by wendtke** [comment]
> @SmogDr - do you want to create a GitHub [organization](https://happygitwithr.com/classroom-overview.html) with the students' private repos, or just have students host their own on their individual profiles? See [here](https://docs.github.com/en/github/setting-up-and-managing-organizations-and-teams/collaborating-with-groups-in-organizations) for more info.

@SmogDr - not sure if this GH ping got lost in the last day. What do you think of the above question?

**Comment by SmogDr** [comment]
I’m new to GitHub organizations but if we can do it with the each student’s repository being private then why not?

--
John Volckens
Professor, Mechanical Engineering
Colorado State University
he, him, his
jv.colostate.edu / @Smogdr

**Comment by wendtke** [comment]
Add Rtools/Rcpp to installation guidance, but RStudio offers to install Rtools automatically

https://thecoatlessprofessor.com/programming/cpp/installing-rtools-for-compiled-code-via-rcpp/
R version 4+ https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

**Comment by wendtke** [comment]
Add `usethis` material (e.g., vaccination) 

https://github.com/uncoast-unconf/uu-2019-day-zero/blob/master/00-preparation/03-usethis/README.md

**Comment by wendtke** [comment]
> Add Rtools/Rcpp to installation guidance, but RStudio offers to install Rtools automatically
> 
> https://thecoatlessprofessor.com/programming/cpp/installing-rtools-for-compiled-code-via-rcpp/
> R version 4+ https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/

From [CRAN](https://cran.r-project.org/bin/macosx/tools/): "CRAN R 4.0.0 builds and higher no longer use any custom compilers and thus this directory is no longer relevant. We now use Apple Xcode 10.1 and GNU Fortran 8.2 from https://github.com/fxcoudert/gfortran-for-macOS/releases. For more details on compiling R, please see also https://mac.R-project.org/tools/"

**Comment by wendtke** [comment]
Closed by #22
