### ISSUE TITLE
Syllabus

### ISSUE THREAD

**Issue by wendtke** [SmogDr/edar_coursebook#21]
@SmogDr, will the syllabus be embedded into `bookdown` or on a separate document? Are there any topics I am planning on putting in the book (e.g., computer set-up instructions) that you would prefer to have in the syllabus?

**Comment by SmogDr** [comment]
@wendtke For now I plan to create a separate document.

**Comment by wendtke** [comment]
Okay, sounds good! I will make PRs for things like #17, and just let me know if you would rather have some of that information in the syllabus.
