### ISSUE TITLE
Exercises: Chapter 3 (import)

### ISSUE THREAD

**Issue by wendtke** [SmogDr/edar_coursebook#4]
Heavily revise Brooke's material OR create new activity. The GBA in-class activity is too long and probably beyond the the scope of this class.

**Comment by wendtke** [comment]
@SmogDr Do you want to keep the [Ebola](https://raw.githubusercontent.com/cmrivers/ebola/master/country_timeseries.csv) and measles data or pick different online data for import practice and class activity? We could use Brooke's in-class activity on measles as the structure for a homework assignment, but do you want to use pollution/respiratory health data or something like that?

**Comment by SmogDr** [comment]
@wendtke I would prefer to use a more engineer-y dataset for that activity.  Is this Chapter 3?  If you can point me to the specific activity/teaching then I can probably come up with a good alternative dataset.

**Comment by wendtke** [comment]
@SmogDr Yes, this is Chapter 3 (data import and wrangling). I started brainstorming activity ideas [in this commit](https://github.com/SmogDr/edar_coursebook/pull/8/commits/d0b039b01b113e01c2a96cd5b9ea6bad8cc29b9c#). I think the in-class activity can include, with a degree of "hand-holding":

- Import local and/or online data file and assign to object name
-- `package::function()` of choice depends on file type.. Do your students typically work with csv, xls/xlsx, MATLAB?
- Examine object structure and column classes with `str()`, `tibble::glimpse()`, `class()`, and the like
- Think about and discuss(?) what kind of data wrangling needs to be done and sketch out the desired dataframe result --or at least list the desired changes (e.g., clean up variable names)
- Practice a few `dplyr` verbs within pipeline to clean up dataframe (e.g., `rename()` column, compute new variable with `mutate()`)
- Bonus question: introduce `janitor` package, especially the `clean_names()` function to clean all variable names at once

Then, for Chapter 3 homework, students can use an R Markdown template I create (unless you want a lesson or two on Rmd added to Weeks 1-2 set-up) to import and wrangle local or online data related to engineering. The homework outline would have instructions but no "hand-holding" demonstrations or function hints. 

What are your thoughts? We can discuss this tomorrow, if you'd like.

**Comment by wendtke** [comment]
@SmogDr provided Fort Collins ozone data. I will add data, code, and related information from email thread to cloud folder (when latter is created).

Additional Ch 3 exercise ideas: 

- Find the maximum and minimum values for the month (and compare them to the standard, even though it’s only a 1-hr measurement)
- Count how many values are above 0.07 in the dataset
- Mutate the sample_measurement column to convert “parts-per-million” into “parts-per-billion” units (i.e., multiply by 1000)
