### ISSUE TITLE
Exercises: Chapter 4 (viz)

### ISSUE THREAD

**Issue by wendtke** [SmogDr/edar_coursebook#5]
JV suggestions:

1. Create a geom_col
2. Create a geom_jitter (mtcars y=mpg, x=cyl)
3. Vary fill, color, line for whole plot
4. Create fill, color aesthetics

**Comment by SmogDr** [comment]
@wendtke Came across a nice progression exercise [here](https://bio304-class.github.io/bio304-fall2017/ggplot-bivariate.html).  This sort of framework might go well but with mtcars or similar engineer-y dataset.

Specifically, everything up to where the trendline gets added.  Those aspects should be introduced later in modeling.
