### ISSUE TITLE
Homework: Chapter 5 (eda1)

### ISSUE THREAD

**Issue by wendtke** [SmogDr/edar_coursebook#6]
JV suggestions:

1. Practice creating histogram, CDF, time-series, and ACF; extract relevant features from each.
2. (hh) Introduce library(gridExtra) and create multi-panel EDA plots
3. Visualize data from a bi-modal distribution (hist, cum dist).
- create data with `rnorm()` with `bind_rows()`; provide external data file 
- all four plots---sometimes EDA plots aren't very informative but worth checking
4. List which plot types discussed in this chapter are enumerative vs. summary.

**Comment by wendtke** [comment]
Recreate [this plot](https://rkabacoff.github.io/datavis/Customizing.html#pre-packaged-themes)?

**Comment by SmogDr** [comment]
Yes.

--
John Volckens
Professor, Mechanical Engineering
Colorado State University
he, him, his
jv.colostate.edu / @Smogdr

**Comment by wendtke** [comment]
> Recreate [this plot](https://rkabacoff.github.io/datavis/Customizing.html#pre-packaged-themes)?

Consider for Chapter 7
