### ISSUE TITLE
Rendering book to PDF 

### ISSUE THREAD

**Issue by wendtke** [SmogDr/edar_coursebook#9]
From what I can tell, there are some structural issues with rendering the `bookdown` book to PDF or "all formats". Have you tried it, @SmogDr, or do you use the `gitbook` option with `rmarkdown::render_site(output_format = 'bookdown::gitbook', encoding = 'UTF-8')` each time?

**Comment by SmogDr** [comment]
From what I recall, I saw this issue a while back but didn't explore it fully because I never intended to publish a pdf version of this book.

**Comment by wendtke** [comment]
Then we will ignore it for now!
